CREATE TABLE VENDOR (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Num VARCHAR(50),
    Name VARCHAR(255),
    PRIMARY KEY (ID)
);
INSERT INTO VENDOR (Num, Name)
SELECT DISTINCT
    VENDOR_NO,
    VENDOR_NAME
FROM LEDGER
ORDER BY VENDOR_NO ASC;

ALTER TABLE LEDGER
ADD COLUMN VENDOR_ID INT UNSIGNED NULL AFTER VENDOR_NO;

UPDATE LEDGER
JOIN VENDOR
    ON LEDGER.VENDOR_NO = VENDOR.Num
    AND LEDGER.VENDOR_NAME = VENDOR.Name
SET LEDGER.VENDOR_ID = VENDOR.ID;

ALTER TABLE LEDGER
ADD CONSTRAINT fk_vendor
    FOREIGN KEY (VENDOR_ID)
    REFERENCES VENDOR(ID);

ALTER TABLE LEDGER
DROP COLUMN VENDOR_NO,
DROP COLUMN VENDOR_NAME;