SELECT
  YEAR (ACCOUNT_PAID) AS y,
  MONTH (ACCOUNT_PAID) AS m,
  CAST(SUM(NET_AMOUNT) * 100 AS SIGNED) AS net_cents,
  CAST(
    SUM(
      CASE
        WHEN NET_AMOUNT > 0 THEN NET_AMOUNT
        ELSE 0
      END
    ) * 100 AS SIGNED
  ) AS outflow_cents
FROM
  LEDGER
WHERE
  ACCOUNT_RE = 4
  AND ACCOUNT_PAID >= ?
  AND ACCOUNT_PAID < ?
GROUP BY
  YEAR (ACCOUNT_PAID),
  MONTH (ACCOUNT_PAID)
ORDER BY
  y ASC,
  m ASC