INSERT INTO
  LEDGER (
    PURCHASE_ORDER,
    VENDOR_ID,
    INVOICE_NO,
    INVOICE_NO_1,
    INVOICE_NO_2,
    INVOICE_NO_3,
    INVOICE_DATE,
    ACCOUNT_RE,
    ACCOUNT_OL1,
    ACCOUNT_OL1_FUNC,
    ACCOUNT_OL2,
    ACCOUNT_FUND,
    ACCOUNT_DEPT,
    ACCOUNT_NO,
    ACCOUNT_PAID,
    NET_AMOUNT,
    CHECK_NO,
    CHECK_DATE,
    DESCRIPTION,
    BATCH
  )
SELECT
  ls.PURCHASE_ORDER,
  v.ID,
  ls.INVOICE_NO,
  ls.INVOICE_NO_1,
  ls.INVOICE_NO_2,
  ls.INVOICE_NO_3,
  ls.INVOICE_DATE,
  ls.ACCOUNT_RE,
  ls.ACCOUNT_OL1,
  ls.ACCOUNT_OL1_FUNC,
  ls.ACCOUNT_OL2,
  ls.ACCOUNT_FUND,
  ls.ACCOUNT_DEPT,
  ls.ACCOUNT_NO,
  ls.ACCOUNT_PAID,
  ls.NET_AMOUNT,
  ls.CHECK_NO,
  ls.CHECK_DATE,
  ls.DESCRIPTION,
  ls.BATCH
FROM
  LEDGER_STAGE ls
  JOIN VENDOR v ON v.Num = ls.VENDOR_NO
  AND v.Name = ls.VENDOR_NAME
WHERE
  ls.STAGE_ID = ?