SELECT
  COA_DEPT.ID AS dept_id,
  COA_DEPT.Name AS dept,
  COA_FUNC.ID AS func_id,
  COA_FUNC.Name AS func,
  CAST(
    SUM(
      CASE
        WHEN LEDGER.ACCOUNT_PAID >= ?
        AND LEDGER.ACCOUNT_PAID < ?
        AND LEDGER.NET_AMOUNT > 0 THEN LEDGER.NET_AMOUNT
        ELSE 0
      END
    ) * 100 AS SIGNED
  ) AS current_month_outflow_cents,
  CAST(
    SUM(
      CASE
        WHEN LEDGER.ACCOUNT_PAID >= ?
        AND LEDGER.ACCOUNT_PAID < ?
        AND LEDGER.NET_AMOUNT > 0 THEN LEDGER.NET_AMOUNT
        ELSE 0
      END
    ) * 100 AS SIGNED
  ) AS fytd_outflow_cents,
  CAST(
    SUM(
      CASE
        WHEN LEDGER.ACCOUNT_PAID >= ?
        AND LEDGER.ACCOUNT_PAID < ?
        AND LEDGER.NET_AMOUNT > 0 THEN LEDGER.NET_AMOUNT
        ELSE 0
      END
    ) * 100 AS SIGNED
  ) AS prior_fytd_outflow_cents
FROM
  LEDGER
  INNER JOIN COA_DEPT ON LEDGER.ACCOUNT_DEPT = COA_DEPT.ID
  INNER JOIN COA_FUNC ON LEDGER.ACCOUNT_OL1_FUNC = COA_FUNC.ID
WHERE
  LEDGER.ACCOUNT_RE = 4
  AND LEDGER.ACCOUNT_PAID >= ?
  AND LEDGER.ACCOUNT_PAID < ?
GROUP BY
  COA_DEPT.ID,
  COA_DEPT.Name,
  COA_FUNC.ID,
  COA_FUNC.Name
ORDER BY
  fytd_outflow_cents DESC